# Bandit Security Linter Configuration
# https://bandit.readthedocs.io/en/latest/config.html

# Tests to skip
skips: ['B101', 'B601']  # Skip assert and shell injection for examples

# Tests to run (leave empty to run all)
tests: []

# Directories to exclude
exclude_dirs: ['tests', '__pycache__', '.git']

# Baseline file for ignoring known issues
# baseline: bandit-baseline.json

# Severity levels: LOW, MEDIUM, HIGH
# Confidence levels: LOW, MEDIUM, HIGH